name: Test JSON Merge
on: 
  workflow_call:
    secrets:
      token:
        description: token
        required: true
  push:
    
jobs:
  merge_json_job:
    runs-on: ubuntu-latest
    name: Merge json files
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TEST_ACTION_GH_PAT }}  # TODO: Change this to org secret
          path: './json-temp/'  
          repository: 'teamkfinteg/json-test-data'  # TODO: Update to kf org

      - name: Merge input-file into library-file json data
        id: merge-json
        uses: teamkfinteg/hello-world-javascript-action@v0.1.8 # TODO: Update to kf org when transfered
        with:
          input-file: integ-store-types.json
          library-file: ./json-temp/store-types/store-types.json

      - uses: Keyfactor/add-and-commit@v7.5.0
        with:
          author_name: 'fiddlermikey'
          author_email: 'fiddlermikey@gmail.com'
          branch: 'main'
          message: ${{ format('Merged the {0} stores-type.json', github.event.repository.name) }}
          add: 'store-types/store-types.json'
          cwd: './json-temp/'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
