name: Test JSON Merge
on: [push, workflow_dispatch]

jobs:
  merge_json_job:
    runs-on: ubuntu-latest
    name: Merge json files
    steps:
      - uses: actions/checkout@v2
      - name: Merge input-file into library-file json data
        id: merge-json
        uses: teamkfinteg/hello-world-javascript-action@v0.1.6
        with:
          input-file: integ-store-types.json
          library-file: master-store-types.json
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
